import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import {Parallax, ParallaxLayer} from '@react-spring/parallax'

export default function Home() {
    return (
        <div>
      <Head>
        <title>Create Portfolio app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{flex: 1, display: 'flex', minHeight: '100vh', flexDirection: 'column', backgroundColor: 'red'}}>

        <div style={{flex: 1}} className={styles.container}>
      <Parallax style={{color: "blue", flex: 1}} pages={4}>
        <ParallaxLayer>
            <h1 className={styles.title} >Hello from Arpan</h1>
        </ParallaxLayer>
        <ParallaxLayer offset={1} >
            <h1 className={styles.title} >Hello Again</h1>
        </ParallaxLayer>
      </Parallax>
    </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    );
}
